/** Slugs that correspond to dedicated route files in src/app/(frontend)/. */
export const RESERVED_SLUGS = new Set([
  'about',
  'officers',
  'projects',
  'events',
  'announcements',
  'documents',
  'scholarships',
  'members',
  'account',
  'admin',
  'advanced-admin',
  'dashboard',
  'join',
  'contact',
  'login',
  'payload-admin',
  'signin',
  'sign-in',
  'log-in',
  'donate',
])
